#Requires -RunAsAdministrator
<#
.SYNOPSIS
    One-shot setup for whatsapp-mcp-extended on Windows.
    Run once after cloning: .\setup.ps1
    Re-run at any time to update scheduled tasks.
.DESCRIPTION
    1. Configures Docker Desktop to auto-start at login
    2. Copies .env.example -> .env if .env is missing
    3. Runs `uv sync` to ensure the Python venv is healthy
    4. Registers three Windows Task Scheduler jobs:
       - WA-Bridge-Startup   : runs at login, opens web UI if bridge needs pairing
       - WA-Bridge-Monitor   : runs every 10 min, auto-reconnects or alerts if unhealthy
       - WA-Bridge-UvSync    : runs daily, keeps the Python venv in sync
#>

param(
    [string]$ProjectPath = $PSScriptRoot
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$BRIDGE_URL  = "http://127.0.0.1:8180"
$WEBUI_URL   = "http://127.0.0.1:8090"
$SCRIPTS_DIR = Join-Path $ProjectPath "scripts"
$ENV_FILE    = Join-Path $ProjectPath ".env"
$ENV_EXAMPLE = Join-Path $ProjectPath ".env.example"
$MCP_DIR     = Join-Path $ProjectPath "whatsapp-mcp-server"

Write-Host ""
Write-Host "=== whatsapp-mcp-extended setup ===" -ForegroundColor Cyan
Write-Host "Project: $ProjectPath" -ForegroundColor Gray
Write-Host ""

# ── 1. Docker Desktop auto-start ──────────────────────────────────────────────
$dockerSettings = "$env:APPDATA\Docker\settings.json"
if (Test-Path $dockerSettings) {
    try {
        $s = Get-Content $dockerSettings -Raw | ConvertFrom-Json
        if ($s.autoStart -ne $true) {
            $s.autoStart = $true
            $s | ConvertTo-Json -Depth 20 | Set-Content $dockerSettings
            Write-Host "[OK] Docker Desktop: auto-start enabled" -ForegroundColor Green
        } else {
            Write-Host "[OK] Docker Desktop: auto-start already enabled" -ForegroundColor Gray
        }
    } catch {
        Write-Host "[WARN] Could not update Docker Desktop settings: $_" -ForegroundColor Yellow
        Write-Host "       Manually enable: Docker Desktop -> Settings -> General -> Start at login"
    }
} else {
    Write-Host "[WARN] Docker Desktop settings not found at $dockerSettings" -ForegroundColor Yellow
    Write-Host "       Manually enable: Docker Desktop -> Settings -> General -> Start at login"
}

# ── 2. .env bootstrap ─────────────────────────────────────────────────────────
if (-not (Test-Path $ENV_FILE)) {
    if (Test-Path $ENV_EXAMPLE) {
        Copy-Item $ENV_EXAMPLE $ENV_FILE
        Write-Host "[OK] Created .env from .env.example — edit it to set API_KEY" -ForegroundColor Green
        Write-Host "     $ENV_FILE" -ForegroundColor Yellow
    } else {
        Write-Host "[WARN] No .env.example found — create $ENV_FILE manually" -ForegroundColor Yellow
    }
} else {
    Write-Host "[OK] .env already exists" -ForegroundColor Gray
}

# ── 3. uv sync ────────────────────────────────────────────────────────────────
$uvPath = Get-Command uv -ErrorAction SilentlyContinue
if ($uvPath) {
    Write-Host "[..] Running uv sync in whatsapp-mcp-server..." -ForegroundColor Gray
    Push-Location $MCP_DIR
    try {
        & uv sync 2>&1 | Out-Null
        Write-Host "[OK] uv sync complete" -ForegroundColor Green
    } catch {
        Write-Host "[WARN] uv sync failed: $_" -ForegroundColor Yellow
    } finally {
        Pop-Location
    }
} else {
    Write-Host "[WARN] uv not found in PATH — skipping venv sync" -ForegroundColor Yellow
    Write-Host "       Install uv: https://docs.astral.sh/uv/getting-started/installation/"
}

# ── 4. Create scripts directory and healthcheck.ps1 ──────────────────────────
if (-not (Test-Path $SCRIPTS_DIR)) {
    New-Item -ItemType Directory -Path $SCRIPTS_DIR | Out-Null
}

# Write healthcheck.ps1 into scripts/ so Task Scheduler can call it
$healthcheckPath = Join-Path $SCRIPTS_DIR "healthcheck.ps1"
@"
# Auto-generated by setup.ps1 — do not edit path references manually, re-run setup.ps1
param([switch]`$Startup)

`$BRIDGE_URL = "$BRIDGE_URL"
`$WEBUI_URL  = "$WEBUI_URL"
`$LOG_FILE   = Join-Path "$ProjectPath" "logs" "healthcheck.log"
`$API_KEY    = ""

# Read API_KEY from .env
`$envFile = "$ENV_FILE"
if (Test-Path `$envFile) {
    Get-Content `$envFile | ForEach-Object {
        if (`$_ -match '^API_KEY\s*=\s*(.+)$') { `$API_KEY = `$Matches[1].Trim('"').Trim("'") }
    }
}

`$headers = @{}
if (`$API_KEY) { `$headers["X-API-Key"] = `$API_KEY }

# On startup, wait for Docker containers to come up
if (`$Startup) { Start-Sleep -Seconds 90 }

# Ensure log directory exists
`$logDir = Split-Path `$LOG_FILE
if (-not (Test-Path `$logDir)) { New-Item -ItemType Directory -Path `$logDir | Out-Null }

function Write-Log([string]`$msg) {
    "`$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') `$msg" | Add-Content `$LOG_FILE
}

try {
    `$resp = Invoke-RestMethod -Uri "`$BRIDGE_URL/api/connection" -Headers `$headers -TimeoutSec 5 -ErrorAction Stop
    `$connected   = `$resp.connected
    `$needsPairing = `$resp.needs_pairing

    if (`$needsPairing) {
        Write-Log "ALERT: bridge needs pairing (Store.ID is nil) — opening web UI"
        # Show Windows toast notification
        [Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType = WindowsRuntime] | Out-Null
        [Windows.Data.Xml.Dom.XmlDocument, Windows.Data.Xml.Dom.XmlDocument, ContentType = WindowsRuntime] | Out-Null
        `$xml = [Windows.Data.Xml.Dom.XmlDocument]::new()
        `$xml.LoadXml('<toast><visual><binding template="ToastGeneric"><text>WhatsApp Bridge</text><text>Needs re-pairing — opening web UI now</text></binding></visual></toast>')
        `$toast = [Windows.UI.Notifications.ToastNotification]::new(`$xml)
        [Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier("WhatsApp Bridge").Show(`$toast)
        # Open web UI in default browser
        Start-Process `$WEBUI_URL
    } elseif (-not `$connected) {
        Write-Log "INFO: bridge disconnected (has session) — triggering reconnect"
        Invoke-RestMethod -Uri "`$BRIDGE_URL/api/reconnect" -Method Post -Headers `$headers -TimeoutSec 5 -ErrorAction SilentlyContinue | Out-Null
    } else {
        Write-Log "OK: connected=true needs_pairing=false"
    }
} catch {
    Write-Log "ERROR: could not reach bridge at `$BRIDGE_URL — `$_"
    if (`$Startup) {
        Write-Log "INFO: Docker may still be starting — no action taken on startup"
    }
}
"@ | Set-Content $healthcheckPath -Encoding UTF8

Write-Host "[OK] healthcheck.ps1 written to $healthcheckPath" -ForegroundColor Green

# ── 5. Register Task Scheduler jobs ───────────────────────────────────────────
function Register-WaTask {
    param(
        [string]$TaskName,
        [string]$Description,
        $Trigger,
        [string]$Arguments
    )
    $action = New-ScheduledTaskAction `
        -Execute "powershell.exe" `
        -Argument "-NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$healthcheckPath`" $Arguments"
    $settings = New-ScheduledTaskSettingsSet `
        -ExecutionTimeLimit (New-TimeSpan -Minutes 5) `
        -MultipleInstances IgnoreNew `
        -StartWhenAvailable
    $principal = New-ScheduledTaskPrincipal `
        -UserId ([System.Security.Principal.WindowsIdentity]::GetCurrent().Name) `
        -LogonType Interactive `
        -RunLevel Limited

    if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    }
    Register-ScheduledTask `
        -TaskName    $TaskName `
        -Description $Description `
        -Action      $action `
        -Trigger     $Trigger `
        -Settings    $settings `
        -Principal   $principal | Out-Null
    Write-Host "[OK] Scheduled task: $TaskName" -ForegroundColor Green
}

# Job A: at-login startup check (90s delay baked into script via -Startup flag)
Register-WaTask `
    -TaskName    "WA-Bridge-Startup" `
    -Description "Check WhatsApp bridge health at login; open web UI if pairing needed" `
    -Trigger     (New-ScheduledTaskTrigger -AtLogOn) `
    -Arguments   "-Startup"

# Job B: every 10 minutes
Register-WaTask `
    -TaskName    "WA-Bridge-Monitor" `
    -Description "Check WhatsApp bridge health every 10 min; auto-reconnect or alert" `
    -Trigger     (New-ScheduledTaskTrigger -RepetitionInterval (New-TimeSpan -Minutes 10) -Once -At (Get-Date)) `
    -Arguments   ""

# Job D: restart bridge on wake-from-sleep (fixes Docker DNS stuck state)
$wakeScript = Join-Path $SCRIPTS_DIR "wake-restart.ps1"
@"
# Auto-generated by setup.ps1
# Wait for Docker's WSL2 networking to reinitialize after wake
Start-Sleep -Seconds 30
Set-Location "$ProjectPath"
docker compose restart whatsapp-bridge
"@ | Set-Content $wakeScript -Encoding UTF8

$wakeTriggerXml = @"
<EventTrigger>
  <Enabled>true</Enabled>
  <Subscription>&lt;QueryList&gt;&lt;Query Id='0' Path='System'&gt;&lt;Select Path='System'&gt;*[System[Provider[@Name='Microsoft-Windows-Power-Troubleshooter'] and EventID=1]]&lt;/Select&gt;&lt;/Query&gt;&lt;/QueryList&gt;</Subscription>
</EventTrigger>
"@
try {
    $trigClass = Get-CimClass -ClassName MSFT_TaskEventTrigger -Namespace Root/Microsoft/Windows/TaskScheduler
    $wakeTrigger = New-CimInstance -CimClass $trigClass -ClientOnly
    $wakeTrigger.Subscription = "<QueryList><Query Id='0' Path='System'><Select Path='System'>*[System[Provider[@Name='Microsoft-Windows-Power-Troubleshooter'] and EventID=1]]</Select></Query></QueryList>"
    $wakeTrigger.Enabled = $true

    $wakeAction = New-ScheduledTaskAction `
        -Execute "powershell.exe" `
        -Argument "-NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$wakeScript`""
    $wakeSettings = New-ScheduledTaskSettingsSet `
        -ExecutionTimeLimit (New-TimeSpan -Minutes 5) `
        -MultipleInstances IgnoreNew `
        -StartWhenAvailable
    $wakePrincipal = New-ScheduledTaskPrincipal `
        -UserId ([System.Security.Principal.WindowsIdentity]::GetCurrent().Name) `
        -LogonType Interactive `
        -RunLevel Limited

    if (Get-ScheduledTask -TaskName "WA-Bridge-WakeRestart" -ErrorAction SilentlyContinue) {
        Unregister-ScheduledTask -TaskName "WA-Bridge-WakeRestart" -Confirm:$false
    }
    Register-ScheduledTask `
        -TaskName    "WA-Bridge-WakeRestart" `
        -Description "Restart whatsapp-bridge on wake-from-sleep to fix Docker DNS stuck state (waits 30s for WSL2 network)" `
        -Action      $wakeAction `
        -Trigger     $wakeTrigger `
        -Settings    $wakeSettings `
        -Principal   $wakePrincipal | Out-Null
    Write-Host "[OK] Scheduled task: WA-Bridge-WakeRestart" -ForegroundColor Green
} catch {
    Write-Host "[WARN] Could not register WA-Bridge-WakeRestart: $_" -ForegroundColor Yellow
    Write-Host "       Register manually: schtasks /create /tn WA-Bridge-WakeRestart /tr `"powershell -File '$wakeScript'`" /sc ONEVENT /ec System /mo `"*[System[Provider[@Name='Microsoft-Windows-Power-Troubleshooter'] and EventID=1]]`""
}

# Job C: daily uv sync
$uvExe = if ($uvPath) { $uvPath.Source } else { "uv" }
$uvAction = New-ScheduledTaskAction `
    -Execute    $uvExe `
    -Argument   "sync" `
    -WorkingDirectory $MCP_DIR
$uvSettings = New-ScheduledTaskSettingsSet -StartWhenAvailable
$uvPrincipal = New-ScheduledTaskPrincipal `
    -UserId ([System.Security.Principal.WindowsIdentity]::GetCurrent().Name) `
    -LogonType Interactive -RunLevel Limited
$uvTrigger = New-ScheduledTaskTrigger -Daily -At "03:00"
if (Get-ScheduledTask -TaskName "WA-Bridge-UvSync" -ErrorAction SilentlyContinue) {
    Unregister-ScheduledTask -TaskName "WA-Bridge-UvSync" -Confirm:$false
}
Register-ScheduledTask `
    -TaskName    "WA-Bridge-UvSync" `
    -Description "Daily uv sync to keep whatsapp-mcp-server venv healthy" `
    -Action      $uvAction `
    -Trigger     $uvTrigger `
    -Settings    $uvSettings `
    -Principal   $uvPrincipal | Out-Null
Write-Host "[OK] Scheduled task: WA-Bridge-UvSync" -ForegroundColor Green

# ── Done ──────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "=== Setup complete ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor White
Write-Host "  1. Edit .env and set API_KEY (if not already done)"
Write-Host "  2. docker-compose up -d"
Write-Host "  3. Open http://127.0.0.1:8090 and scan QR to pair"
Write-Host ""
Write-Host "Scheduled tasks registered:" -ForegroundColor White
Write-Host "  WA-Bridge-Startup     — runs at login, opens web UI if bridge needs pairing"
Write-Host "  WA-Bridge-Monitor     — runs every 10 min, auto-reconnects if disconnected"
Write-Host "  WA-Bridge-WakeRestart — runs on wake-from-sleep, restarts bridge (30s delay)"
Write-Host "  WA-Bridge-UvSync      — runs daily at 3am, keeps Python venv in sync"
Write-Host ""
Write-Host "Quick commands:" -ForegroundColor White
Write-Host "  make status     — check bridge connection state"
Write-Host "  make pair PHONE=+60123456789   — pair via phone code (no QR scan)"
Write-Host "  make reconnect  — force reconnect"
Write-Host "  make logs       — tail bridge logs"
Write-Host ""
